export const wilayats = [
  'skikda',
  'alger',
  'constantine',
  'oran',
  'Mila',
  'skikda',
  'alger',
  'constantine',
  'oran',
  'Mila',
  'skikda',
  'alger',
  'constantine',
  'oran',
  'Mila',
  'skikda',
  'alger',
  'constantine',
  'oran',
  'Mila',
]

export const codePostal = [{ 21042: 'Filfila' }, { 21002: 'azzaba' }]

export const CountriesData = [
  {
    id: 1,
    name: 'Algeria',
    wilayats: [
      {
        id: 1,
        name: 'Skikda',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 2,
        name: 'Algiers',
        commute: [
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Oued righa', code: 98765 },
        ],
      },
      {
        id: 3,
        name: 'Oran',
        commute: [
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Ouled Fayet', code: 22233 },
        ],
      },
      {
        id: 4,
        name: 'Annaba',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
        ],
      },
      {
        id: 5,
        name: 'Constantine',
        commute: [
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
        ],
      },
      {
        id: 6,
        name: 'Tlemcen',
        commute: [
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
        ],
      },
      {
        id: 7,
        name: 'Bejaia',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
        ],
      },
      {
        id: 8,
        name: 'Blida',
        commute: [
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Oued righa', code: 98765 },
        ],
      },
      {
        id: 9,
        name: 'Bordj Bou Arreridj',
        commute: [
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Bab Ezzouar', code: 12345 },
        ],
      },
      {
        id: 10,
        name: 'Bouira',
        commute: [
          { name: 'Souahlia', code: 33344 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
        ],
      },
      {
        id: 11,
        name: 'Chlef',
        commute: [
          { name: 'Souahlia', code: 33344 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 12,
        name: 'Djelfa',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 13,
        name: 'El Oued',
        commute: [
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 14,
        name: 'Guelma',
        commute: [
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 101,
        name: 'Skikda',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 102,
        name: 'Algiers',
        commute: [
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Oued righa', code: 98765 },
        ],
      },
      {
        id: 103,
        name: 'Oran',
        commute: [
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Ouled Fayet', code: 22233 },
        ],
      },
      {
        id: 104,
        name: 'Annaba',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
        ],
      },
      {
        id: 105,
        name: 'Constantine',
        commute: [
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
        ],
      },
      {
        id: 106,
        name: 'Tlemcen',
        commute: [
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
        ],
      },
      {
        id: 107,
        name: 'Bejaia',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
        ],
      },
      {
        id: 108,
        name: 'Blida',
        commute: [
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Oued righa', code: 98765 },
        ],
      },
      {
        id: 109,
        name: 'Bordj Bou Arreridj',
        commute: [
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Bab Ezzouar', code: 12345 },
        ],
      },
      {
        id: 1010,
        name: 'Bouira',
        commute: [
          { name: 'Souahlia', code: 33344 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
        ],
      },
      {
        id: 1011,
        name: 'Chlef',
        commute: [
          { name: 'Souahlia', code: 33344 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 1012,
        name: 'Djelfa',
        commute: [
          { name: 'Oued righa', code: 98765 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'El Bouni', code: 11122 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 1013,
        name: 'El Oued',
        commute: [
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Oued righa', code: 98765 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Souahlia', code: 33344 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
      {
        id: 1014,
        name: 'Guelma',
        commute: [
          { name: 'Ouled Fayet', code: 22233 },
          { name: 'Bab Ezzouar', code: 12345 },
          { name: 'Sidi Bel Abbes', code: 56789 },
          { name: 'Oued righa', code: 98765 },
          { name: 'El Bouni', code: 11 },
        ],
      },
    ],
  },
]
